---
- name: Create remnanode directory
  ansible.builtin.file:
    path: "{{ remnanode_path }}"
    owner: root
    group: root
    mode: '0700'
    state: directory

- name: Create compose file
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ remnanode_path }}/docker-compose.yaml"
    owner: root
    group: root
    mode: '0600'

- name: Create Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ remnanode_path }}/Caddyfile"
    owner: root
    group: root
    mode: '0600'

- name: Create env file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ remnanode_path }}/.env"
    owner: root
    group: root
    mode: '0600'

- name: Start remnanode
  community.docker.docker_compose_v2:
    project_src: "{{ remnanode_path }}"
    remove_orphans: true
    state: present

- name: Configure logrotate
  ansible.builtin.import_tasks: logrotate.yaml
  when: remnanode_enable_logrotate
