---
- name: Create Caddy directory
  ansible.builtin.file:
    path: "{{ remnawave_caddy_path }}"
    owner: root
    group: root
    mode: '0700'
    state: directory

- name: Create compose file
  ansible.builtin.copy:
    src: docker-compose.yaml
    dest: "{{ remnawave_caddy_path }}/docker-compose.yaml"
    owner: root
    group: root
    mode: '0600'

- name: Create Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ remnawave_caddy_path }}/Caddyfile"
    owner: root
    group: root
    mode: '0600'

- name: Create env file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ remnawave_caddy_path }}/.env"
    owner: root
    group: root
    mode: '0600'

- name: Start Caddy
  community.docker.docker_compose_v2:
    project_src: "{{ remnawave_caddy_path }}"
    remove_orphans: true
    state: present
